### ISSUE TITLE
국가 필터 및 정렬 기능 구현

### ISSUE THREAD

**Issue by rhsiddlsidhd** [elice-study-3rd/country-search-app#8]
## 설명
국가 필터/정렬 기능을 구현한다.

## 작업 사항
- [x] 필터 및 순서 정렬 드롭다운 UI 구현
- [x] all or 지역별 필터 or 기타 필터 ( 독립, 비독립 국가(independent true/false))
- [x] 표시 순서 변경 기능 구현(국가명, 인구)

## 기타 사항
작업 방식은 미정 (API로 부터 받은 데이터를 가공하여 렌더링 함수 호출할 지 or API로부터 정제된 data를 받아올 지)

**Comment by Ji-hoon** [comment]
국가 정보를 fetcher를 통해 반환받을 떄, promise를 써서 국가명 오름/내림차순 정렬 그리고 인구 오름/내림차순 정렬 까지도 반환 받을 수 있도록 함수를 추가해두려고 합니다. feature/api-sort 브랜치가 적용되면 사용 검토 부탁드려요.

**Comment by rhsiddlsidhd** [comment]
네!! 해보도록 할게요

**Comment by rhsiddlsidhd** [comment]
> 국가 정보를 fetcher를 통해 반환받을 떄, promise를 써서 국가명 오름/내림차순 정렬 그리고 인구 오름/내림차순 정렬 까지도 반환 받을 수 있도록 함수를 추가해두려고 합니다. feature/api-sort 브랜치가 적용되면 사용 검토 부탁드려요.

네 !
